### ISSUE TITLE
Number of steps?

### ISSUE THREAD

**Issue by G-force78** [PhilSad/stable-diffusion-infinite-outpainting-video#1]
Hi thanks for this looks very cool and the collab is straight forward. 
Just a query about the steps, in the collab is originally set to 50000, this seems very high (although I have no idea really) how many was your example video? is there a recommended minimum? Im just testing it at 500 now.

Also, where would I link to a folder of pre-generated images?

Thanks

**Comment by PhilSad** [comment]
Hi, sorry I mixed things up and ended with commiting the 5000 by mistake.
It takes 30 sec/step for the outpainting and 1.5 min/step for generating video. So for testing purpoise about 5 is enought. The youtube video is 52 steps and took ~2 hours total.

> Also, where would I link to a folder of pre-generated images?

I don't undurstand this part,

**Comment by PhilSad** [comment]
Hi, sorry I mixed things up and ended with commiting the 5000 by mistake. It's fixed now thanks for pointing it out.
It takes 30 sec/step for the outpainting and 1.5 min/step for generating video. So for testing purpose, about 5 is enough. The youtube video is 52 steps and took ~2 hours total.

> Also, where would I link to a folder of pre-generated images?

I don't undurstand this part, what do you want to do?

**Comment by G-force78** [comment]
> Hi, sorry I mixed things up and ended with commiting the 5000 by mistake. It's fixed now thanks for pointing it out. It takes 30 sec/step for the outpainting and 1.5 min/step for generating video. So for testing purpose, about 5 is enough. The youtube video is 52 steps and took ~2 hours total.
> 
> > Also, where would I link to a folder of pre-generated images?
> 
> I don't undurstand this part, what do you want to do?

Ok thanks. 

Instead of generating images  by using the collab input.txt I would like to just upload some of my images and use them for it, is that possible?

**Comment by PhilSad** [comment]
It does not support that directly and you'll need an intermediary step to make the same postprocess as the video generation notebook expect HQ triplet pictures.

This step is done with the function `super_resolution.generate_base_images_ia`. Use it on a list of consecutive 512x512 images and it will process them correctly (You need the GPU for this step).
Then save your processed images in a drive folder. Name them 0.jpeg, 1.jpeg, 2.jpeg, ... in the same order as in the outputed list and you'll be able to use the video generation notebook.

But yeah the code should support that in a future update

**Comment by PhilSad** [comment]
Added the following functionnalities:
* Save the intermediary 512x512 images
* Process existing 512x512 images for the video generation (in the `colab_infinite_outpaint_generate_base_images` colab

Let me know if there is any issues
